name: Tweet on Push

on:
  push:
    branches:
      - main # または使用しているブランチ

jobs:
  tweet:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz
          pip install tweepy
          pip install python-dotenv
          touch .env
          echo "TWITTER_CONSUMER_API_KEY=${{ secrets.TWITTER_CONSUMER_API_KEY }}" >> .env
          echo "TWITTER_CONSUMER_API_SECRET_KEY=${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}" >> .env
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> .env
          echo "TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}" >> .env

      - name: Run script
        run: |
          python main.py
